trigger:
- develop

pool:
  name: mrgnc-self-hosted

steps:
- script: |
    cd infra/terraform
    terraform init
    terraform validate
    terraform plan -var-file="environments/dev.tfvars"
  displayName: 'Terraform plan'
  env:
    ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

- script: |
    cd infra/terraform
    terraform apply -auto-approve -var-file="environments/dev.tfvars"
  displayName: 'Terraform apply'
  env:
    ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)